export const blogPost = [
  {
    name: "template",
    type_project: "template",
    titulo: "template",
    img_tumbnail: "https://i.ibb.co/fnxvswS/kda-2x.jpg",
    img_header: "https://ttager.netlify.app/img/oaAhri4.jpg",
    img_next: "https://i.ibb.co/fnxvswS/kda-2x.jpg",
    link: 'projects/template',
    show: false,
  },
  {
    name: "the-one",
    type_project: "Client",
    titulo: "The One",
    img_tumbnail: "https://i.ibb.co/FXBMxr8/flor-2x.jpg",
    img_header: "https://i.ibb.co/FXBMxr8/flor-2x.jpg",
    img_next: "https://i.ibb.co/FXBMxr8/flor-2x.jpg",
    link: "projects/the-one",
    show: true,
  },
  {
    name: "portfolio-project",
    type_project: "Personal",
    titulo: "Portfolio",
    img_tumbnail: "https://i.ibb.co/0J2Ntfn/hu-Tao-background-desktop.jpg",
    img_header: "https://i.ibb.co/0J2Ntfn/hu-Tao-background-desktop.jpg",
    img_next: "https://i.ibb.co/0J2Ntfn/hu-Tao-background-desktop.jpg",
    link: "projects/portfolio-project",
    show: true,
  },
  // {
  //   name: "Ahrigato",
  //   type_project: "Personal",
  //   titulo: "Ahrigato",
  //   img: "https://i.ibb.co/b2JvX8R/coven-2x.jpg",
  //   link: "projects/Ahrigato",
  // },
  // {
  //   name: "spirit-blossom",
  //   type_project: "Client",
  //   titulo: "Flor del espiritu",
  //   img: "https://i.ibb.co/FXBMxr8/flor-2x.jpg",
  //   link: "projects/spirit-blossom",
  // },
];
// export const blogPost = {
//   TheOne: {
//     type_project: "Client",
//     titulo: "The One",
//     img: "https://ttager.netlify.app/img/oaAhri4.jpg",
//     link: "projects/the-one",
//   },
//   MyPortafolio: {
//     type_project: "Personal",
//     titulo: "Portfolio",
//     img: "https://i.ibb.co/0J2Ntfn/hu-Tao-background-desktop.jpg",
//     link: "projects/portfolio-project",
//   },
//   Ahrigato: {
//     type_project: "Personal",
//     titulo: "Ahrigato",
//     img: "https://i.ibb.co/b2JvX8R/coven-2x.jpg",
//     link: "projects/Ahrigato",
//   },
//   FS: {
//     type_project: "Client",
//     titulo: "Flor del espiritu",
//     img: "https://i.ibb.co/FXBMxr8/flor-2x.jpg",
//     link: "projects/spirit-blossom",
//   },
// };
